name: (📡) Create GitHub Release Draft

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-github-release:
    uses: sitepark-com/project-workflow/.github/workflows/github-create-release-draft.yml@main
