name: Maven Verify

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'ci(release):')"

    steps:
      - uses: actions/checkout@v3

      - name: Get JDK Version from pom.xml
        id: jdk
        uses: QwerMike/xpath-action@v1
        with:
        filename: 'pom.xml'
        expression: '//project/properties/maven.compiler.release/text()'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ jdk.result }} 
          distribution: 'adopt'
          cache: 'maven'
          
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Build and verify with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2


