name: Release-Published

on:
   release:
      types:
         - published
         - created
         - edited
         - deleted

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Maven Artifact
        run:
           echo "publish maven artifact $GITHUB_REF"
